---
- name: copy apt sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: Install additional host packages
  apt:
    name: ['git','screen','python-pip']
    update_cache: yes
    state: present
    force: yes

- name: Install Python docker
  command: pip install docker 

- name: Enable NetQ stats collection 
  command: "{{item}}"
  with_items:
    - systemctl enable netq-stats-pushd.service 
    - systemctl start netq-stats-pushd.service

- name: Create Grafana storage
  docker_volume:
    name: grafana-storage

- name: Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    ports:
    - "3000:3000"
    volumes:
    - grafana-storage:/var/lib/grafana
    env:
      GF_SERVER_ROOT_URL: 'http://grafana.server.name'
      GF_SECURITY_ADMIN_PASSWORD: 'CumulusLinux!' 

- name: Pause to let container start 
  pause:
    seconds: 60 

- name: Create Grafana NetQ datasource
  grafana_datasource:
    name: NetQ
    grafana_url: http://localhost:3000
    grafana_password: 'CumulusLinux!'
    ds_type: influxdb
    url: http://192.168.200.250:8086
    database: netq
    state: present

- name: Import Grafana dashboard 
  grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "admin"
    grafana_password: 'CumulusLinux!'
    org_id: 1
    state: present
    overwrite: yes
    message: Updated by ansible
    path: ip-fabric.json
  tags:
    - test
  register: shell_result

- debug:
    var: shell_result.stdout_lines
...
