---
######
# Seems gitlab runner it a bit too fast, checking if all hosts are up
#####
- hosts: network 
  become: yes
  gather_facts: false
  tasks:
    - name: Wait for hosts to be up 
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 15 
        timeout: 120
      ignore_errors: true

#####
# Host config from NetQ demo, needs to move to separate role
#####
- hosts: oob 
  become: true
  roles:
  - oob-mgmt-server

- hosts: netq-ts
  become: true
  roles:
  - setup-netq-ts
  - app-grafana
  - app-netbox

- hosts: spines,superspine
  become: true
  roles:
  - setup-switch
  - switch-spine

- hosts: leafs,edge,router
  become: true 
  roles:
  - setup-switch
  - switch-leaf

- hosts: servers-rack1,servers-rack3 
  become: true 
  roles:
  - setup-server
  - app-netq
  - server-multitenant

- hosts: servers-rack2 
  become: true 
  roles:
  - setup-server
  - app-netq
  - server-evpn
  reboot:
    reboot_timeout: 1200
    test_command: mount
...
