---
- apt_repository:
    repo: ppa:ansible/ansible 

- name: Install additional host packages
  apt:
    name: ['ansible','iperf3','libnl-route-3-200','libnl-route-3-dev','lldpd'] 
    update_cache: yes
    state: present

- name: Correct LLDP Settings
  lineinfile:
    dest: /etc/lldpd.d/port_info.conf
    line: "configure lldp portidsubtype ifname"
    create: yes
  notify: restart LLDP

- name: Apply LLDP Settings
  meta: flush_handlers

- name: Install python packages for ifupdown2
  apt: 
    name: ['python2.7','python-argcomplete','python-ipaddr']
    state: present

- name: Remove ifupdown1
  apt: 
    name: ['ifupdown','ifenslave']
    state: absent

- name: Copy deb packages
  copy: src={{ item }} dest=/home/cumulus/ owner=cumulus
  with_fileglob:
    - files/*.deb

- name: Install ifupdown2 & Vrf tools
  apt: 
    deb: "{{item}}" 
    state: present 
  with_items:
    - /home/cumulus/ifupdown2_1.0~git20170314-1_all.deb
    - /home/cumulus/vrf_1.3_amd64.deb
    - /home/cumulus/mgmt-vrf_1.3_all.deb
    - /home/cumulus/linux-headers-4.19.0-041900_4.19.0-041900.201810221809_all.deb
    - /home/cumulus/linux-headers-4.19.0-041900-generic_4.19.0-041900.201810221809_amd64.deb
    - /home/cumulus/linux-modules-4.19.0-041900-generic_4.19.0-041900.201810221809_amd64.deb
    - /home/cumulus/linux-image-unsigned-4.19.0-041900-generic_4.19.0-041900.201810221809_amd64.deb

- name: Sysctl l3mdev_accept
  sysctl:
    name: net.ipv4.tcp_l3mdev_accept
    value: 1
    state: present
    reload: yes 

- name: Sysctl l3mdev_accept
  sysctl:
    name: net.ipv4.udp_l3mdev_accept
    value: 1
    state: present
    reload: yes 

- name: L4 hash policy 
  sysctl:
    name: net.ipv4.fib_multipath_hash_policy
    value: 1
    state: present
    reload: no

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes

- name: Add dns server 
  lineinfile:
    path: /etc/resolv.conf 
    line: 'nameserver 192.168.200.1 # vrf mgmt'

- name: Reboot system
  reboot:
    reboot_timeout: 1200
    test_command: mount
...
