---
- name: Set IPv4 L4 hashing
  sysctl:
    name: net.ipv4.fib_multipath_hash_policy
    value: 1
    state: present
    reload: yes

- name: Configured NTP in management VRF
  command: "{{item}}"
  with_items:
    - systemctl stop ntp.service
    - systemctl disable ntp.service
    - systemctl enable ntp@mgmt
    - systemctl start ntp@mgmt

- name: copy netq config file
  copy:
    src: netq.yml
    dest: /etc/netq/netq.yml

- name: Configure NetQ in management VRF
  command: "{{item}}"
  with_items:
    - systemctl stop netqd.service
    - systemctl disable netqd.service
    - systemctl stop netq-agent.service
    - systemctl disable netq-agent.service
    - systemctl enable netqd@mgmt
    - systemctl start netqd@mgmt
    - systemctl enable netq-agent@mgmt
    - systemctl start netq-agent@mgmt

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted
